name: C/C++ CI

on:
  push:
    branches:
    - master
    - releases/*

  pull_request:
    branches:
    - master

jobs:
  ubuntu-x86-64:
    name: Ubuntu cross build (x86-64 GCC)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Remove mono runtime
      run: sudo apt-get purge mono-runtime

    - name: Install dependencies
      run: >-
           sudo apt-get update &&
           sudo apt-get install -y --no-install-recommends
           mingw-w64-{x86-64-dev,tools} {gcc,g++,binutils}-mingw-w64-x86-64
           ninja-build python3-pip wine wine-binfmt

    - name: Install newest meson
      run: >-
           sudo pip3 install meson  # --break-system-packages

    - name: Run tests
      run: >-
           meson setup --cross-file meson.cross.x86_64-w64-mingw32
           -Denable-debug-checks=true build_ci
           && meson test -j4 -t8 -Cbuild_ci

  linaro-ubuntu-arm64:
    name: Ubuntu cross build (AArch64 Clang)
    runs-on: ubuntu-latest
    container: linaro/wine-arm64

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: >-
           apt-get update &&
           apt-get install -y --no-install-recommends
           ninja-build python3-pip

    - name: Install newest meson
      run: >-
           pip3 install meson --break-system-packages

    - name: Download llvm-mingw
      run: >-
           wget 'https://github.com/mstorsjo/llvm-mingw/releases/download/20240308/llvm-mingw-20240308-ucrt-ubuntu-20.04-x86_64.tar.xz'
           && tar -xaf llvm-mingw-20240308-ucrt-ubuntu-20.04-x86_64.tar.xz

    - name: Run tests
      run: >-
           export PATH=$(pwd)/llvm-mingw-20240308-ucrt-ubuntu-20.04-x86_64/bin:$PATH;
           meson setup --cross-file meson.cross.aarch64-w64-mingw32
           -Denable-debug-checks=true build_ci
           && meson test -j3 -t24 -Cbuild_ci

  msys2-ucrt64:
    name: MSYS2 native build (x86-64 GCC)
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64

    - name: Install dependencies
      run: >-
           pacman -Sy --noconfirm
           mingw-w64-ucrt-x86_64-{{headers,crt,tools}-git,gcc,meson}

    - name: Run tests
      run: >-
           meson setup -Denable-debug-checks=true build_ci
           && meson test -j4 -t2 -Cbuild_ci

  msys2-mingw32:
    name: MSYS2 native build (i686 GCC)
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32

    - name: Install dependencies
      run: >-
           pacman -Sy --noconfirm
           mingw-w64-i686-{{headers,crt,tools}-git,gcc,meson}

    - name: Run tests
      run: >-
           meson setup -Denable-debug-checks=true build_ci
           && meson test -j4 -t2 -Cbuild_ci

  msys2-clang64:
    name: MSYS2 native build (x86-64 Clang)
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4

    - uses: msys2/setup-msys2@v2
      with:
        msystem: CLANG64

    - name: Install dependencies
      run: >-
           pacman -Sy --noconfirm
           mingw-w64-clang-x86_64-{{headers,crt,tools}-git,clang,meson}

    - name: Run tests
      run: >-
           export CC=clang CXX=clang++;
           meson setup -Denable-debug-checks=true build_ci
           && meson test -j4 -t2 -Cbuild_ci
